name = "helloworld-test-327"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "helloworld-test-327_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "helloworld-test-327.wasm"
command = "npm run build:release"
